auth-proxy/MarkupSafe-3.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 23118
  object_id: 90e64af5-1a04-4f54-75ce-4e5984294f03
  sha: sha256:e17c96c14e19278594aa4841ec148115f9c7615a47382ecb6b82bd8fea3ab0c8
auth-proxy/PyJWT-2.9.0-py3-none-any.whl:
  size: 22344
  object_id: 03d6c41c-a7b5-4eea-6d56-dcbdda1a80c2
  sha: sha256:3b02fb0f44517787776cf48f2ae25d8e14f300e6d7545a4315cee571a415e850
auth-proxy/async_timeout-5.0.1-py3-none-any.whl:
  size: 6233
  object_id: 284b82c8-2538-4c82-481c-b664ae73e151
  sha: sha256:39e3809566ff85354557ec2398b55e096c8364bacac9405a7a1fa429e77fe76c
auth-proxy/blinker-1.8.2-py3-none-any.whl:
  size: 9456
  object_id: 304da490-f8a7-4671-4e54-ba254b83d054
  sha: sha256:1779309f71bf239144b9399d06ae925637cf6634cf6bd131104184531bf67c01
auth-proxy/cachelib-0.13.0-py3-none-any.whl:
  size: 20914
  object_id: 2db07a1a-f13c-4345-6eb5-3b89f3a14c19
  sha: sha256:8c8019e53b6302967d4e8329a504acf75e7bc46130291d30188a6e4e58162516
auth-proxy/certifi-2024.8.30-py3-none-any.whl:
  size: 167321
  object_id: 437fca17-3a4e-4088-6cb4-6cb58ddbe4db
  sha: sha256:922820b53db7a7257ffbda3f597266d435245903d80737e34f8a45ff3e3230d8
auth-proxy/cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 479424
  object_id: 93cbfef5-f135-487b-5d34-ff797b1fbffc
  sha: sha256:b62ce867176a75d03a665bad002af8e6d54644fad99a3c70905c543130e39d93
auth-proxy/charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 143838
  object_id: 1017c0b8-42fb-449f-690c-723e63a56a1d
  sha: sha256:8cda06946eac330cbe6598f77bb54e690b4ca93f593dee1568ad22b04f347c15
auth-proxy/click-8.1.7-py3-none-any.whl:
  size: 97941
  object_id: 079a6e28-41d8-476a-6ed5-d1643cd55a24
  sha: sha256:ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28
auth-proxy/cryptography-43.0.3-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 3977754
  object_id: 9ac4b6d2-490a-408e-5e43-5181234a6883
  sha: sha256:0f996e7268af62598f2fc1204afa98a3b5712313a55c4c9d434aef49cadc91d4
auth-proxy/dnspython-2.7.0-py3-none-any.whl:
  size: 313632
  object_id: e90125a5-031d-4ff3-5cd6-04c2ce84250e
  sha: sha256:b4c34b7d10b51bcc3a5071e7b8dee77939f1e878477eeecc965e9835f63c6c86
auth-proxy/environs-11.0.0-py3-none-any.whl:
  size: 12216
  object_id: 563dfe4d-137a-420b-79cc-56255cb9b25b
  sha: sha256:e0bcfd41c718c07a7db422f9109e490746450da38793fe4ee197f397b9343435
auth-proxy/eventlet-0.37.0-py3-none-any.whl:
  size: 361621
  object_id: 58b99a2a-bcd9-4107-5d06-9378e81078f0
  sha: sha256:801ac231401e41f33a799457c78fdbfabc1c2f28bf9346d4ec4188e9aebc2067
auth-proxy/flask-3.0.3-py3-none-any.whl:
  size: 101735
  object_id: d72bea02-e703-41e3-7727-393ac785b382
  sha: sha256:34e815dfaa43340d1d15a5c3a02b8476004037eb4840b34910c6e21679d288f3
auth-proxy/flask_session-0.8.0-py3-none-any.whl:
  size: 24410
  object_id: be9335c8-8973-4f28-7d4f-0a24080e7acc
  sha: sha256:5dae6e9ddab334f8dc4dea4305af37851f4e7dc0f484caf3351184001195e3b7
auth-proxy/greenlet-3.1.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 660105
  object_id: 23fe2446-463c-453d-4602-967473e7547f
  sha: sha256:99cfaa2110534e2cf3ba31a7abcac9d328d1d9f1b95beede58294a60348fba36
auth-proxy/gunicorn-23.0.0-py3-none-any.whl:
  size: 85029
  object_id: 0e533a60-3225-405d-580b-aebca1ca170d
  sha: sha256:ec400d38950de4dfd418cff8328b2c8faed0edb0d517d3394e457c317908ca4d
auth-proxy/idna-3.10-py3-none-any.whl:
  size: 70442
  object_id: c478b274-01f0-4da9-416b-29dbf9faeb75
  sha: sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3
auth-proxy/itsdangerous-2.2.0-py3-none-any.whl:
  size: 16234
  object_id: 621c689f-6458-4647-4975-3b21087567c9
  sha: sha256:c6242fc49e35958c8b15141343aa660db5fc54d4f13a1db01a3f5891b98700ef
auth-proxy/jinja2-3.1.4-py3-none-any.whl:
  size: 133271
  object_id: ac171432-a4b1-4942-7ea6-815bad96c26a
  sha: sha256:bc5dd2abb727a5319567b7a813e6a2e7318c39f4f487cfe6c89c6f9c7d25197d
auth-proxy/jwcrypto-1.5.6-py3-none-any.whl:
  size: 92520
  object_id: f89dc01d-8c02-4099-7668-08662814b4fe
  sha: sha256:150d2b0ebbdb8f40b77f543fb44ffd2baeff48788be71f67f03566692fd55789
auth-proxy/marshmallow-3.23.1-py3-none-any.whl:
  size: 49488
  object_id: 3ab529b7-9edb-494f-4e51-c09c11e5b392
  sha: sha256:fece2eb2c941180ea1b7fcbd4a83c51bfdd50093fdd3ad2585ee5e1df2508491
auth-proxy/msgspec-0.18.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl:
  size: 212510
  object_id: 211dd7e2-ff78-4903-59a6-60e743cb818f
  sha: sha256:ad237100393f637b297926cae1868b0d500f764ccd2f0623a380e2bcfb2809ca
auth-proxy/packaging-24.1-py3-none-any.whl:
  size: 53985
  object_id: 33d35324-3057-46c7-41df-b72ab75f6fe6
  sha: sha256:5b8f2217dbdbd2f7f384c41c628544e6d52f2d0f53c6d0c3ea61aa5d1d7ff124
auth-proxy/pycparser-2.22-py3-none-any.whl:
  size: 117552
  object_id: 12cb5ff2-a552-45cc-6e0b-5bd45546db6e
  sha: sha256:c3702b6d3dd8c7abc1afa565d7e63d53a1d0bd86cdc24edd75470f4de499cfcc
auth-proxy/python_dotenv-1.0.1-py3-none-any.whl:
  size: 19863
  object_id: d8ef629a-bf23-4b3d-7911-a8f5dc3250a1
  sha: sha256:f7b63ef50f1b690dddf550d03497b66d609393b40b564ed0d674909a68ebf16a
auth-proxy/redis-5.2.0-py3-none-any.whl:
  size: 261428
  object_id: f31e37d3-ea0e-4f5c-4275-3a0540bffab1
  sha: sha256:ae174f2bb3b1bf2b09d54bf3e51fbc1469cf6c10aa03e21141f51969801a7897
auth-proxy/requests-2.32.3-py3-none-any.whl:
  size: 64928
  object_id: 4e5ba60d-0496-4834-49fb-c82f8daa86b0
  sha: sha256:70761cfe03c773ceb22aa2f671b4757976145175cdfca038c02654d061d6dcc6
auth-proxy/typing_extensions-4.12.2-py3-none-any.whl:
  size: 37438
  object_id: 12650ef3-92e2-4432-5f03-a66f5531e9e6
  sha: sha256:04e5ca0351e0f3f85c6853954072df659d0d13fac324d0072316b67d7794700d
auth-proxy/urllib3-2.2.3-py3-none-any.whl:
  size: 126338
  object_id: e445daeb-509c-43a6-7c6f-75c30a99ff72
  sha: sha256:ca899ca043dcb1bafa3e262d73aa25c465bfb49e0bd9dd5d59f1d0acba2f8fac
auth-proxy/werkzeug-3.1.2-py3-none-any.whl:
  size: 224352
  object_id: 45af49a7-9728-4fdb-5576-6627b8e4fbb7
  sha: sha256:4f7d1a5de312c810a8a2c6f0b47e9f6a7cffb7c8322def35e4d4d9841ff85597
awscli-exe-linux-x86_64.zip:
  size: 62186639
  object_id: acf3ef43-9e8d-4749-4daf-7c6edf3a5297
  sha: sha256:fca9d80afb77f4cf5f2df6078b30ebb123b40e5b070ee7c1d5c3fba92d6b3755
jdk-21.0.7_linux-x64_bin.tar.gz:
  size: 197755939
  object_id: 23f844d3-02eb-4ea7-6a13-a8b82e7cb61f
  sha: sha256:332636375b234e56f0198fdea409f896afcc3ce627f9d0b7924cc7b51d50a295
jq-linux-amd64-1.8.1.tar.gz:
  size: 995911
  object_id: fa239437-7080-45f1-6e31-3fa88414b51d
  sha: sha256:bf735e7e23ac7718779966591536a2146b3562349eb2ab85f39724290d9f46a1
logstash/logstash-8.16.1-linux-x86_64.tar.gz:
  size: 428558276
  object_id: 6448195b-fb5b-4a22-5f16-759c29296cf6
  sha: sha256:1245b05b83443c204f355ad8463cf9c9a0e2d6052d51578aeaaaadb7eb6ca214
logstash/logstash-filter-alter-3.0.3.zip:
  size: 7655
  object_id: 552763c7-779b-4ac3-5993-04a06d967c93
  sha: sha256:76cbede4e9b774cadf6260fee4e7430949f77a6c76e7e512212b8ac50c75723a
logstash/logstash-filter-translate-3.4.2.zip:
  size: 649362
  object_id: e9b87119-265c-43ce-788d-5592aabffcb3
  sha: sha256:f465635431b474abaf61c6673d7c91cb5f62b09a193d45a5622342f5a5b967c6
logstash/logstash-input-cloudwatch_logs-1.1.4.zip:
  size: 2469631
  object_id: 737795fb-b4e3-4b7b-6f1d-5b51a54e3cd5
  sha: sha256:8ec9aaf87ac61a7cc8f0caf11e9b837f36e9f571f93bb0aaf1372b3769ce7d8a
logstash/logstash-input-relp-3.0.4.zip:
  size: 44725
  object_id: 2e183484-97da-4e51-4311-51e024d0665b
  sha: sha256:96bb5c75fb0f945b44d23d8da29cd4a7ba235b86d7ad26f3d77d333a8da34163
logstash/logstash-input-syslog-3.6.0.zip:
  size: 605224
  object_id: 8ed631eb-eb7c-47fa-631c-904061ef6412
  sha: sha256:db06d886e62a8718f33cbfd23ab8eabec80c9673fa9346995518e43989d0bbaf
logstash/logstash-input-tcp-6.4.1.zip:
  size: 14501935
  object_id: 77443abb-adce-433c-4789-bc507504e596
  sha: sha256:ca440f035617138c53dc40450802ff058187a4734e177d3f68944bade68acdd4
logstash/logstash-integration-aws-7.1.6.zip:
  size: 2143813
  object_id: da9212f7-36ef-46b6-5480-8f5eaeb9fa9b
  sha: sha256:b80e9f5812aa07c472782193e61ce402b30fa965440e25f002a5af2cf10261b1
logstash/logstash-output-opensearch-2.0.2.zip:
  size: 24204545
  object_id: f15ae09c-ac8c-4dba-51ce-952917dedad6
  sha: sha256:11d471575afb3cf5d6ef26fa112e7c42e38f24d0a02b0a5d9405a5c8d8bb157c
logstash/logstash-output-syslog-3.0.5.zip:
  size: 41727
  object_id: 21474ee6-824a-4547-7f45-b236864358ab
  sha: sha256:80a2b08f2b58ae81c823cc0bb1dd7956fbc173037fc621bfa31af34140724e02
opensearch-3.4.0-linux-x64.tar.gz:
  size: 1101115111
  object_id: 279734b6-145d-4431-5c92-948007eb684a
  sha: sha256:c061ebf4a2a43a9d81cd0a9db2914fc8b2c4b21189801595e6bff30f43a2d7c9
opensearch-dashboards-3.4.0-linux-x64.tar.gz:
  size: 448850112
  object_id: b3666a8d-da39-49c2-55b9-c9554b2bd506
  sha: sha256:266ab69f494ae63fcbc638cd3ac2a108e5e744a88224209e01e388586ea4fb9f
opensearch-dashboards-cf-auth-proxy-0.0.11.tar.gz:
  size: 36275
  object_id: c8408b65-2c08-4d47-731c-fa1dbb7a9747
  sha: sha256:d81c67e7372f250a1c21cf03c6156a7e6e870796a3b87757d2396bf1c2c8853c
opensearch/opensearch-alerting-3.3.1.0.zip:
  size: 14155971
  object_id: 46daa474-cb55-435f-7229-b0541c3f9327
  sha: sha256:88bb4a4e9b82391928af0a353fed31a472bfff4cc1bbd0d36f47aaac0b5c9057
opensearch/opensearch-alerting-3.4.0.0.zip:
  size: 10906114
  object_id: 19287a4d-d141-4bf3-6c25-8247b223bfaf
  sha: sha256:7a2f21cfb2cae91ce02f23be610368c6a8081afeb49fca631dd22f453767585a
opensearch/opensearch-notifications-3.3.1.0.zip:
  size: 23494481
  object_id: 27640f83-a693-451c-7e00-c634c5573d9c
  sha: sha256:7f84e0cf0034db5dfadefb5068006350e82ce5941d8e070bb04f5679a419da6d
opensearch/opensearch-notifications-3.4.0.0.zip:
  size: 42238954
  object_id: 3f9fef28-38c6-4119-4ee5-f4e716e18ec9
  sha: sha256:55a4982752634f5754dd356c59cfa14ac1129dda99e6b7cab6dfe6c11279e4d3
requests/certifi-2023.11.17-py3-none-any.whl:
  size: 162530
  object_id: f2afff72-e415-4390-61c1-eb8010ed4e4a
  sha: sha256:e036ab49d5b79556f99cfc2d9320b34cfbe5be05c5871b51de9329f0603b0474
requests/charset_normalizer-3.3.2-py3-none-any.whl:
  size: 48543
  object_id: 4cb33cab-c554-4a9b-7cf6-236d34d29f3a
  sha: sha256:3e4d1f6587322d2788836a99c69062fbb091331ec940e02d12d179c1d53e25fc
requests/idna-3.6-py3-none-any.whl:
  size: 61567
  object_id: 11c88dd1-f41a-4e60-4a73-cc115d7e2e97
  sha: sha256:c05567e9c24a6b9faaa835c4821bad0590fbb9d5779e7caa6e1cc4978e7eb24f
requests/requests-2.31.0-py3-none-any.whl:
  size: 62574
  object_id: 9137b76d-49e5-4901-4fb6-76c352c89ca9
  sha: sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f
requests/urllib3-2.1.0-py3-none-any.whl:
  size: 104579
  object_id: 291e120e-854f-4599-4be9-85fac7f82bd0
  sha: sha256:55901e917a5896a349ff771be919f8bd99aff50b79fe58fec595eb37bbc56bb3
ruby/rake-13.0.6.gem:
  size: 84992
  object_id: ae89e0d2-b8d0-454f-6eff-6673b2956ada
  sha: sha256:5ce4bf5037b4196c24ac62834d8db1ce175470391026bd9e557d669beeb19097
yq_linux_amd64-4.44.6.tar.gz:
  size: 4196529
  object_id: cc6157b3-5ba0-4996-60e3-d90c8a150110
  sha: sha256:09ea7643cba1cfde4c57abbadbf7fa242d7425db8ee93c0b184d68661cf3b1bd
