opensearch-2.9.0-linux-x64.tar.gz:
  size: 805162121
  object_id: a0062097-fe9f-4720-666f-8fb84933550d
  sha: sha256:03d623c2d99a7100c2f0faddc8ffda8ba27eae8aa63ff6f3f7dad2337be8b68c
opensearch-dashboards-2.9.0-linux-x64.tar.gz:
  size: 314585875
  object_id: 8a7b9858-37a1-4f9e-4d6d-3cbe61433cac
  sha: sha256:f8328b9c1156d254faa561c03cbc51159f5e335812c7b27a98bbe0556b9f030c
