auth-proxy/PyJWT-2.8.0-py3-none-any.whl:
  size: 22591
  object_id: fc779b2c-aa09-417d-4cd1-86c6a08394bd
  sha: sha256:59127c392cc44c2da5bb3192169a91f429924e17aff6534d70fdc02ab3e04320
auth-proxy/certifi-2024.2.2-py3-none-any.whl:
  size: 163774
  object_id: f7c98402-cec5-4c63-77b1-a074f54654af
  sha: sha256:dc383c07b76109f368f6106eee2b593b04a011ea4d55f652c6ca24a754d1cdd1
auth-proxy/charset_normalizer-3.3.2-py3-none-any.whl:
  size: 48543
  object_id: cac75579-13b3-4a38-53b2-88e39d10435e
  sha: sha256:3e4d1f6587322d2788836a99c69062fbb091331ec940e02d12d179c1d53e25fc
auth-proxy/environs-10.3.0-py3-none-any.whl:
  size: 12565
  object_id: a9a15277-5dc6-4c98-59bf-4d7abf33e368
  sha: sha256:feeaf28f17fd0499f9cd7c0fcf408c6d82c308e69e335eb92d09322fc9ed8138
auth-proxy/flask-3.0.2-py3-none-any.whl:
  size: 101300
  object_id: f8d36a81-6c42-4740-74f8-0ecd513acde4
  sha: sha256:3232e0e9c850d781933cf0207523d1ece087eb8d87b23777ae38456e2fbe7c6e
auth-proxy/gunicorn-21.2.0-py3-none-any.whl:
  size: 80176
  object_id: bf45b039-dbd5-4553-51ff-d64ae6101aac
  sha: sha256:3213aa5e8c24949e792bcacfc176fef362e7aac80b76c56f6b5122bf350722f0
auth-proxy/idna-3.6-py3-none-any.whl:
  size: 61567
  object_id: 876717a1-96c3-4a0c-73f9-c2fb58a39aeb
  sha: sha256:c05567e9c24a6b9faaa835c4821bad0590fbb9d5779e7caa6e1cc4978e7eb24f
auth-proxy/marshmallow-3.20.2-py3-none-any.whl:
  size: 49449
  object_id: d9b8c3e4-8b80-48ec-524b-8a68ce4277b5
  sha: sha256:c21d4b98fee747c130e6bc8f45c4b3199ea66bc00c12ee1f639f0aeca034d5e9
auth-proxy/packaging-23.2-py3-none-any.whl:
  size: 53011
  object_id: bcc10197-aaf6-46b4-4362-1c461f4da6aa
  sha: sha256:8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7
auth-proxy/python_dotenv-1.0.1-py3-none-any.whl:
  size: 19863
  object_id: 60b1a827-b2f9-474a-464f-b59480e3e7ce
  sha: sha256:f7b63ef50f1b690dddf550d03497b66d609393b40b564ed0d674909a68ebf16a
auth-proxy/redis-5.0.1-py3-none-any.whl:
  size: 250272
  object_id: 9a84cd2c-dc4f-470c-7da5-bec2b513bc14
  sha: sha256:ed4802971884ae19d640775ba3b03aa2e7bd5e8fb8dfaed2decce4d0fc48391f
auth-proxy/requests-2.31.0-py3-none-any.whl:
  size: 62574
  object_id: cd38b65b-b321-4d4c-425e-f6393c85bf62
  sha: sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f
auth-proxy/urllib3-2.2.0-py3-none-any.whl:
  size: 120877
  object_id: ab44aca9-1188-40fe-4d0c-22a1e3a8f8b4
  sha: sha256:ce3711610ddce217e6d113a2732fafad960a03fd0318c91faa79481e35c11224
curator-opensearch-0.0.11.tar.gz:
  size: 247372
  object_id: 3cb859ae-895b-4e55-4119-f3dd963e4b00
  sha: sha256:a1626a3464ad5575c00c0540adda78c62185bf0e0c52ced5dc181a0a81070ff9
curator/vendor/Cython-0.29.36.tar.gz:
  size: 2097760
  object_id: 278ed8dc-40f8-4c8a-7877-8cb1329a4474
  sha: sha256:41c0cfd2d754e383c9eeb95effc9aa4ab847d0c9747077ddd7c0dcb68c3bc01f
curator/vendor/PyYAML-6.0.1.tar.gz:
  size: 125201
  object_id: 340f3b7f-2bd6-42e0-7f78-28596c4163df
  sha: sha256:bfdf460b1736c775f2ba9f6a92bca30bc2095067b8a9d77876d1fad6cc3b4a43
curator/vendor/boto3-1.28.40-py3-none-any.whl:
  size: 135762
  object_id: 07717c77-dae6-44de-42fd-742a1c9b894d
  sha: sha256:bd7c760afb195eaeaab907dc6b2c21fa64ddbba3fed4a869e80d820ddbd6cc70
curator/vendor/botocore-1.31.40-py3-none-any.whl:
  size: 11164205
  object_id: 6cb3aa24-2c37-49e1-7fe2-247959772e7b
  sha: sha256:df766969f0d9ef9eda1a9c9946e0e173c10199f37a9e4c92861f11ddb5c9e702
curator/vendor/certifi-2023.7.22-py3-none-any.whl:
  size: 158334
  object_id: 3e70cca5-28f6-4d8b-6c73-b77ecab3b62b
  sha: sha256:92d6037539857d8206b8f6ae472e8b77db8058fec5937a1ef3f54304089edbb9
curator/vendor/chardet-5.2.0-py3-none-any.whl:
  size: 199385
  object_id: df02eabc-7ff7-4424-55bc-24aa29640147
  sha: sha256:e1cf59446890a00105fe7b7912492ea04b6e6f06d4b742b2c788469e34c82970
curator/vendor/charset_normalizer-3.2.0-py3-none-any.whl:
  size: 46668
  object_id: 1459959c-d724-4aff-7f52-adc6b6e16124
  sha: sha256:8e098148dd37b4ce3baca71fb394c81dc5d9c7728c95df695d2dca218edf40e6
curator/vendor/click-7.1.2-py2.py3-none-any.whl:
  size: 82780
  object_id: 7030b9c2-a5a7-444a-6b7e-ff4049562b3a
  sha: sha256:dacca89f4bfadd5de3d7489b7c8a566eee0d3676333fbb50030263894c38c0dc
curator/vendor/docutils-0.20.1-py3-none-any.whl:
  size: 572666
  object_id: 86bf09ce-07c6-419f-5c00-4ab9acc2cc8d
  sha: sha256:96f387a2c5562db4476f09f13bbab2192e764cac08ebbf3a34a95d9b1e4a59d6
curator/vendor/flit_core-3.8.0.tar.gz:
  size: 41224
  object_id: 940bcba2-17b3-4d77-5153-89d703f40ff8
  sha: sha256:b305b30c99526df5e63d6022dd2310a0a941a187bd3884f4c8ef0418df6c39f3
curator/vendor/idna-3.4-py3-none-any.whl:
  size: 61538
  object_id: 7116348d-1840-43da-6f92-29b2839c0780
  sha: sha256:90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2
curator/vendor/jmespath-1.0.1-py3-none-any.whl:
  size: 20256
  object_id: ba0684fc-a3ca-4110-407a-0faed339ec8f
  sha: sha256:02e2e4cc71b5bcab88332eebf907519190dd9e6e82107fa7f83b1003a6252980
curator/vendor/opensearch_py-2.3.1-py2.py3-none-any.whl:
  size: 327343
  object_id: 9b95f6ca-f3ae-4575-6e9d-0a50ca95bf06
  sha: sha256:eafbc5d56a7ca696afba7d77bcda1bbb849050cbf9265d57d8476576cb576395
curator/vendor/python_dateutil-2.8.2-py2.py3-none-any.whl:
  size: 247702
  object_id: cb990ba6-15c7-4edc-657c-677a26119d77
  sha: sha256:961d03dc3453ebbc59dbdea9e4e11c5651520a876d0f4db161e8674aae935da9
curator/vendor/requests-2.31.0-py3-none-any.whl:
  size: 62574
  object_id: fa836242-28ce-4bac-6481-7569704dcd43
  sha: sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f
curator/vendor/requests_aws4auth-1.2.3-py2.py3-none-any.whl:
  size: 24708
  object_id: 74438842-148f-4745-48cd-0ca0d5df72b6
  sha: sha256:8070a5207e95fa5fe88e87d9a75f34e768cbab35bb3557ef20cbbf9426dee4d5
curator/vendor/s3transfer-0.6.2-py3-none-any.whl:
  size: 79765
  object_id: aaed6545-d8ba-45c4-4219-48b1d0868206
  sha: sha256:b014be3a8a2aab98cfe1abc7229cc5a9a0cf05eb9c1f2b86b230fd8df3f78084
curator/vendor/setuptools-69.0.3.tar.gz:
  size: 2219609
  object_id: 82547212-6589-4e56-775e-fe8131f1f3c9
  sha: sha256:be1af57fc409f93647f2e8e4573a142ed38724b8cdd389706a867bb4efcf1e78
curator/vendor/six-1.16.0-py2.py3-none-any.whl:
  size: 11053
  object_id: 23f63c14-a88f-452d-66f9-3d0ce44cc4e3
  sha: sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254
curator/vendor/urllib3-1.26.5-py2.py3-none-any.whl:
  size: 138144
  object_id: 38253a32-ae62-422c-52ef-c20a71843760
  sha: sha256:753a0374df26658f99d826cfe40394a686d05985786d946fbe4165b5148f5a7c
curator/vendor/voluptuous-0.13.1-py3-none-any.whl:
  size: 29790
  object_id: dd2c1d70-b9c7-431e-5285-1ff9e0c7fc26
  sha: sha256:4b838b185f5951f2d6e8752b68fcf18bd7a9c26ded8f143f92d6d28f3921a3e6
curator/vendor/wheel-0.41.2.tar.gz:
  size: 98050
  object_id: 418dced9-9c61-4579-5744-23f6d1221554
  sha: sha256:0c5ac5ff2afb79ac23ab82bab027a0be7b5dbcf2e54dc50efe4bf507de1f7985
logstash/logstash-8.9.2-linux-x86_64.tar.gz:
  size: 346522558
  object_id: 61bc773e-e0a2-4cf5-416e-0964a3d83978
  sha: sha256:86eb38b40f66dea4f3c747582c53f574d88ea0c57b8f60325baa00022cbba998
logstash/logstash-filter-alter-3.0.3.zip:
  size: 7655
  object_id: 552763c7-779b-4ac3-5993-04a06d967c93
  sha: sha256:76cbede4e9b774cadf6260fee4e7430949f77a6c76e7e512212b8ac50c75723a
logstash/logstash-filter-translate-3.4.2.zip:
  size: 649362
  object_id: e9b87119-265c-43ce-788d-5592aabffcb3
  sha: sha256:f465635431b474abaf61c6673d7c91cb5f62b09a193d45a5622342f5a5b967c6
logstash/logstash-input-relp-3.0.4.zip:
  size: 44725
  object_id: 2e183484-97da-4e51-4311-51e024d0665b
  sha: sha256:96bb5c75fb0f945b44d23d8da29cd4a7ba235b86d7ad26f3d77d333a8da34163
logstash/logstash-input-syslog-3.6.0.zip:
  size: 605224
  object_id: 8ed631eb-eb7c-47fa-631c-904061ef6412
  sha: sha256:db06d886e62a8718f33cbfd23ab8eabec80c9673fa9346995518e43989d0bbaf
logstash/logstash-output-opensearch-2.0.2.zip:
  size: 24204545
  object_id: f15ae09c-ac8c-4dba-51ce-952917dedad6
  sha: sha256:11d471575afb3cf5d6ef26fa112e7c42e38f24d0a02b0a5d9405a5c8d8bb157c
logstash/logstash-output-syslog-3.0.5.zip:
  size: 41727
  object_id: 21474ee6-824a-4547-7f45-b236864358ab
  sha: sha256:80a2b08f2b58ae81c823cc0bb1dd7956fbc173037fc621bfa31af34140724e02
opensearch-2.9.0-linux-x64.tar.gz:
  size: 805162121
  object_id: a0062097-fe9f-4720-666f-8fb84933550d
  sha: sha256:03d623c2d99a7100c2f0faddc8ffda8ba27eae8aa63ff6f3f7dad2337be8b68c
opensearch-dashboards-2.9.0-linux-x64.tar.gz:
  size: 314585875
  object_id: 8a7b9858-37a1-4f9e-4d6d-3cbe61433cac
  sha: sha256:f8328b9c1156d254faa561c03cbc51159f5e335812c7b27a98bbe0556b9f030c
opensearch-dashboards-cf-auth-proxy.tar.gz:
  size: 733255
  object_id: 8cab5732-c284-4674-6d77-40965de2cf17
  sha: sha256:afdeb01edb5f19e1693b253bdb114a0bcd37fc301a2eb5cbac5a74b95f145175
requests/certifi-2023.11.17-py3-none-any.whl:
  size: 162530
  object_id: f2afff72-e415-4390-61c1-eb8010ed4e4a
  sha: sha256:e036ab49d5b79556f99cfc2d9320b34cfbe5be05c5871b51de9329f0603b0474
requests/charset_normalizer-3.3.2-py3-none-any.whl:
  size: 48543
  object_id: 4cb33cab-c554-4a9b-7cf6-236d34d29f3a
  sha: sha256:3e4d1f6587322d2788836a99c69062fbb091331ec940e02d12d179c1d53e25fc
requests/idna-3.6-py3-none-any.whl:
  size: 61567
  object_id: 11c88dd1-f41a-4e60-4a73-cc115d7e2e97
  sha: sha256:c05567e9c24a6b9faaa835c4821bad0590fbb9d5779e7caa6e1cc4978e7eb24f
requests/requests-2.31.0-py3-none-any.whl:
  size: 62574
  object_id: 9137b76d-49e5-4901-4fb6-76c352c89ca9
  sha: sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f
requests/urllib3-2.1.0-py3-none-any.whl:
  size: 104579
  object_id: 291e120e-854f-4599-4be9-85fac7f82bd0
  sha: sha256:55901e917a5896a349ff771be919f8bd99aff50b79fe58fec595eb37bbc56bb3
ruby/rake-13.0.6.gem:
  size: 84992
  object_id: ae89e0d2-b8d0-454f-6eff-6673b2956ada
  sha: sha256:5ce4bf5037b4196c24ac62834d8db1ce175470391026bd9e557d669beeb19097
